environment:
  profile: local
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS XXX} %-5level [%X{tenantId}] %logger{36} - %msg%n"
  level:
    com:
      imatia:
        implatform:
          rowbot2:
            api:
              core:
                services:
                  externalccc: INFO
    org.springframework.boot.autoconfigure: INFO
importers:
  page_size: 10000
  metadata:
    samplesPerColumn: 5
    sampleLength: 15
  mysql:
    timeout: 5
retries:
  default:
    max_attempts: 5
    ms_to_retry: 3
server:
  port: 8087

rowbot2-application:
  server:
    protocol: http
    host: localhost
    port: 8080