dataengine: #TODO: necesario?
  protocol: http
  host: localhost
  port: 8128
  jwt:
    pass: dataenginejwtpass
ccc: #TODO: necesario?
  server:
    protocol: http
    host: localhost
    port: 8083
environment:
  profile: local
logging:
  level:
    com.imatia: DEBUG
    org.springframework.boot.autoconfigure: INFO
server:
  port: 8083
