app:
  async:
    thread-name-prefix: async-
    core-size: 4
    max-size: 12
    queue-capacity: 200
    keep-alive: 30s
    await-termination: true
    await-termination-period: 10s
build:
  version: '@project.version@'
environment:
  profile: ${ENVIRONMENT_PROFILE:#{'production'}}
logging:
  level:
    root: INFO
server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: rowbot2-data-importer
  jackson:
    serialization:
      indent_output: true
    default-property-inclusion: non_null
  datasource:
    embedded-database-connection: none
  jpa:
    hibernate:
      ddl-auto: none
      defer-datasource-initialization: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'
  main:
    allow-circular-references: true #TODO: review that