environment:
  profile: staging
logging:
  level:
    com.imatia: DEBUG
    org.springframework.boot.autoconfigure: INFO
  file:
    name: /opt/rowbot2-data-importer/logs/rowbot2-data-importer.log


  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30
      file-name-pattern: /opt/rowbot2-data-importer/logs/rowbot2-data-importer-%d{yyyy-MM-dd}.%i.log.gz
management:
  security:
    enabled: false
  server:
    base-path: /
    port: 8081
    servlet:
      context-path: /
  endpoints:
    web:
      base-path: /management
rowbot2-application:
  server:
    protocol: ${ROWBOT2_APPLICATION_SERVER_PROTOCOL}
    host: ${ROWBOT2_APPLICATION_SERVER_HOST}
    port: ${ROWBOT2_APPLICATION_SERVER_PORT}
importers:
  page_size: ${IMPORTERS_PAGE_SIZE}
  metadata:
    samplesPerColumn: 5
    sampleLength: 15
retries:
  default:
    max_attempts: ${RETRIES_DEFAULT_MAX_ATTEMPTS}
    ms_to_retry: ${RETRIES_DEFAULT_MS_TO_RETRY}