apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "selectorLabels" . | nindent 8 }}
{{- if .Values.podsLabels }}
{{ toYaml .Values.podsLabels | indent 6 }}
{{- end }}
{{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
    {{- if .Values.storage.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "fullname" . }}-pvc
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if .Values.storage.enabled }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.storage.mountPath }}
        {{- end }}
        {{- if .Values.configmap.enabled }}
          envFrom:
          - configMapRef:
              name: {{ .Values.configmap.name | default (printf "%s-config" (include "fullname" .)) }}
        {{- end }}
          env:
        {{- if .Values.jvmOptions }}
          - name: JVM_OPTIONS
            value: {{ .Values.jvmOptions }}
        {{- end }}
          - name: VERSION
            value: {{ .Chart.Version }}
{{- range $pkey, $pval := .Values.env }}
          - name: {{ $pkey }}
            value: {{ quote $pval }}
{{- end }}
          - name: NAME
            value: {{ (printf "%s" (include "fullname" .)) }}
          - name: HOST
            value: {{ .Values.ingress.host }}
        {{- if .Values.jwt.enabled }}
          - name: JWT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.jwt.secret | default (printf "%s-jwt-secret" (include "fullname" .)) }}
                key: password
        {{- end }}
        {{- if .Values.micrometer.metrics.tags.application }}
          - name: METRIC_TAG_APPLICATION
            value: {{ .Values.micrometer.metrics.tags.application }}
        {{- end }}
        {{- if .Values.grafana.enabled }}
          - name: GRAFANA_SERVER
            value: {{ .Values.grafana.server }}
          - name: GRAFANA_ADMIN_API_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.grafana.secret | default (printf "%s-tm" (include "fullname" .))  }}
                key: apiKey
          - name: GRAFANA_DATASOURCE_NAME
            value: {{ .Values.grafana.datasourceName }}
        {{- end }}
        {{- if .Values.kafka.enabled }}
          - name: KAFKA_SERVER
            value: {{ .Values.kafka.server }}
          - name: KAKFA_SERVER
            value: {{ .Values.kafka.server }}
          - name: SCHEMA_REGISTRY_URL
            value: {{ .Values.kafka.schemaRegistryUrl }}
        {{- end }}
        {{- if .Values.tenantManager.enabled }}
          - name: TENANT_MANAGER_URL
            value: {{ .Values.tenantManager.url }}
        {{- if eq .Values.tenantManager.authType "basic" }}
          - name: TENANT_MANAGER_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.tenantManager.secret | default (printf "%stm-secret" (include "fullname" .))  }}
                key: user
          - name: TENANT_MANAGER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.tenantManager.secret | default  (printf "%stm-secret" (include "fullname" .))  }}
                key: password
        {{- else if eq .Values.tenantManager.authType "secret" }}
          - name: TENANT_MANAGER_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ .Values.tenantManager.secret | default  (printf "%stm-secret" (include "fullname" .))  }}
                key: secret
        {{- end }}
        {{- end }}
        {{- if .Values.tenantManagement.enabled }}
          - name: APPLICATIONS_USER_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.tenantManagement.secret | default (printf "%s-secret" (include "fullname" .))  }}
                key: user
          - name: APPLICATIONS_USER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.tenantManagement.secret | default  (printf "%s-secret" (include "fullname" .))  }}
                key: password
        {{- if .Values.tenantManagement.marketplace.enabled }}
          - name: MARKETPLACE_USER_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.tenantManagement.secret | default (printf "%s-secret" (include "fullname" .))  }}
                key: marketplace-user
          - name: MARKETPLACE_USER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.tenantManagement.secret | default  (printf "%s-secret" (include "fullname" .))  }}
                key: marketplace-password
        {{- end }}
        {{- if .Values.tenantManagement.advanced }}
        {{- $notifications := .Values.tenantManagement.notifications | default dict }}
          - name: NOTIFICATIONS_EMAIL_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ $notifications.secret | default (printf "%s-notifications-secret" (include "fullname" .))  }}
                key: user
          - name: NOTIFICATIONS_EMAIL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ $notifications.secret | default (printf "%s-notifications-secret" (include "fullname" .))  }}
                key: password
        {{- $marketplace := .Values.tenantManagement.marketplace | default dict }}
          - name: MARKETPLACE_SERVICE
            value: {{ $marketplace.url }}
          - name: MARKETPLACE_ORGANIZATION
            valueFrom:
              secretKeyRef:
                name: {{ $marketplace.secret | default (printf "%s-marketplace-secret" (include "fullname" .))  }}
                key: organization
          - name: MARKETPLACE_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ $marketplace.secret | default (printf "%s-marketplace-secret" (include "fullname" .))  }}
                key: user
          - name: MARKETPLACE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ $marketplace.secret | default (printf "%s-marketplace-secret" (include "fullname" .))  }}
                key: password
        {{- end }}
        {{- end }}
        {{- if .Values.s3.enabled }}
          - name: S3_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.s3.secret | default (printf "%s-s3-secret" (include "fullname" .))  }}
                key: accessKey
          - name: S3_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.s3.secret | default  (printf "%s-s3-secret" (include "fullname" .))  }}
                key: secretKey
        {{- end }}
          ports:
          - name: http
            containerPort: {{ .Values.service.internalPort }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.probePath | default .Values.probePath }}
              port: {{ .Values.probePort | default .Values.service.internalPort }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.probePath | default .Values.probePath }}
              port: {{ .Values.probePort | default .Values.service.internalPort }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
