package com.imatia.implatform.rowbot2.data.importer.application.services.base;

import com.imatia.implatform.rowbot2.data.importer.domain.model.base.BaseDomainObject;
import com.imatia.implatform.rowbot2.data.importer.application.dto.ContentPageDataElementDTO;
import com.imatia.implatform.rowbot2.data.importer.domain.model.exception.IdNotPresentException;
import com.imatia.implatform.rowbot2.data.importer.domain.model.exception.IdPresentException;
import com.imatia.implatform.rowbot2.data.importer.infrastructure.out.jpa.entity.base.BaseDatabaseEntity;
import com.imatia.implatform.rowbot2.data.importer.domain.model.exception.IdNotExistentOnDBException;
import com.imatia.implatform.rowbot2.data.importer.domain.model.exception.ValidationException;
import com.imatia.implatform.rowbot2.data.importer.infrastructure.out.jpa.mapper.base.CycleAvoidingMappingContext;
import com.imatia.implatform.rowbot2.data.importer.infrastructure.out.jpa.mapper.base.DetailMapper;
import com.imatia.implatform.rowbot2.data.importer.infrastructure.out.jpa.mapper.base.SimpleMapper;
import com.imatia.implatform.rowbot2.data.importer.infrastructure.out.jpa.repository.base.DatabaseEntityRepository;
import lombok.AccessLevel;
import lombok.NoArgsConstructor;
import lombok.NonNull;
import lombok.RequiredArgsConstructor;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Objects;
import java.util.Optional;

/**
 * Abstract generic class for services able to do CRUD operations, its purpose is to encapsulate logic used across different services
 *
 * @param <E> the entity type
 * @param <R> the repository type
 */
@Service
//TODO: transactional
////TODO: transactional
//@Transactional("multiTenantTransactionManager") ("multiTenantTransactionManager")
@RequiredArgsConstructor
@NoArgsConstructor(access = AccessLevel.PROTECTED)
public abstract class AbstractCRUDServiceImpl<E extends BaseDomainObject, DBO extends BaseDatabaseEntity, R extends DatabaseEntityRepository<DBO>> implements CRUDService<E, Long> {
	@Autowired
	@NonNull
	protected R repo;

	@Autowired
	@NonNull
	protected SimpleMapper<DBO, E> mapper;

	@Autowired
	@NonNull
	protected DetailMapper<DBO, E> detailMapper;

	@Override
	public E create(final E entity) {
		String error = validateForCreation(entity);
		if(error != null){
			throw new ValidationException(error);
		}
		Optional.ofNullable(entity.getId()).ifPresent(id -> {
			throw new IdPresentException("Autogenerated ids fields should not be specified at creations");
		});
		return fromDBO(repo.save(toDBO(entity)));
	}

	@Override
	public Optional<E> read(final Long entityId) {
		return repo.findById(entityId)
				.map(this::fromDBO);
	}

	@Override
	public Page<E> find(String search, Pageable pageable) {
		return fromDBOPage(Objects.isNull(search) ?
				repo.findAll(pageable) :
				repo.findBySubstring(search, pageable));
	}

	@Override
	public void delete(final Long entityId) {
		if (repo.existsById(entityId)) {
			repo.deleteById(entityId);
		} else {
			throw new IdNotExistentOnDBException(this.getClass().getSimpleName(), entityId);
		}
	}

	@Override
	public Integer delete(final List<Long> entityIds){
		return repo.deleteByIdIn(entityIds);
	}

	@Override
	public E update(final E entity) {
		String error = validateForUpdate(entity);
		if(error != null){
			throw new ValidationException(error);
		}
		Boolean doesEntityExists = Optional.ofNullable(entity.getId())
				.map(id -> repo.existsById(id))
				.orElseThrow(() -> new IdNotPresentException("Id field is mandatory at updates"));
		if (!doesEntityExists) {
			throw new IdNotExistentOnDBException(this.getClass().getSimpleName(), entity.getId());
		}
		DBO toSaveDbo = toDBO(entity);
		return fromDBO(repo.save(toSaveDbo));
	}

	/**
	 * This method is designed to be overrided when mapstruct cant do some of the mapping steps
	 * or we want another different mapping approach
	 */
	protected DBO toDBO(E entity){
		return detailMapper.toDBO(entity, new CycleAvoidingMappingContext());
	}

	/**
	 * This method is designed to be overrided when mapstruct cant do some of the mapping steps
	 * or we want another different mapping approach
	 */
	protected E fromDBO(DBO dbo){
		return detailMapper.fromDBO(dbo, new CycleAvoidingMappingContext());
	}

	/**
	 * This method is designed to be overrided when mapstruct cant do some of the mapping steps
	 * or we want another different mapping approach
	 */
	protected Page<E> fromDBOPage(Page<DBO> dboPage){
		return mapper.fromDBOPage(dboPage);
	}

	protected String validateForCreation(E entity){
		return null;
	}

	protected String validateForUpdate(E entity){
		return null;
	}

	protected <PE> ContentPageDataElementDTO<PE> toContentPageDataElementDTO(PE pageElement){
		return ContentPageDataElementDTO.<PE>builder()
				.data(pageElement)
				.build();
	}
}
